version: '3.7'

services:
  clean-api:
    container_name: clean-api-server
    build:
      target: development
    command: yarn dev
    volumes:
      - ../src:/usr/src/app/src
      - ../.env:/usr/src/app/.env
    networks:
      - clean-api-network
  clean-api-db:
    container_name: clean-api-mongo
    image: 'mongo:4.4.0-bionic'
    ports:
      - '27018:27017'
    volumes:
      - './data:/data/db'
    restart: on-failure

networks:
  clean-api-network:
    driver: bridge
