version: '3.7'

services:
  clean-api:
    container_name: clean-api-server
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - clean-api-db
  clean-api-db:
    container_name: clean-api-mongo
    image: 'mongo:4.4.0-bionic'
    ports:
      - '27018:27017'
    volumes:
      - './data:/data/db'
    restart: always

networks:
  clean-api-network:
    driver: bridge
