version: '3.7'

services:
  clean-api:
    container_name: clean-api-server
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - clean-api-db

networks:
  clean-api-network:
    driver: bridge
