FROM node:16-alpine AS base
WORKDIR /usr/src/app
COPY package.json yarn.lock tsconfig.json ./

FROM base as development
ENV NODE_ENV=development
COPY .env .
RUN yarn install

FROM base as build
RUN yarn build

FROM build AS production
ENV NODE_ENV=production
COPY --from=build /usr/src/app/dist /usr/src/app/dist
COPY .env.production ./
RUN yarn install --production
CMD ["yarn", "start"]
